name: Notify cpms-web on Push

on:
  push:
    branches:
      - develop

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger cpms-web action
        run: |
          curl -L -X POST \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: token ${{ secrets.WEB_TRIGGER_PAT }}" \
               https://api.github.com/repos/powernai/cpms-web/dispatches \
               -d '{"event_type": "potree-update"}'
        env:
          WEB_TRIGGER_PAT: ${{ secrets.WEB_TRIGGER_PAT }}
