name: Notify cpms-webs on Push

on:
  push:
    branches:
      - develop

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger cpms-web action
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          --data '{"event_type": "potree-update"}' \
          https://api.github.com/repos/powernai/cpms-web/dispatches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
