name: Notify cpms-web on Push

on:
  push:
    branches:
      - develop

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger cpms-web github action
        run: |
          curl -L -X POST \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               https://api.github.com/repos/powernai/cpms-web/dispatches \
               -d '{"event_type": "potree-update"}'
